# Generated by Django 4.1 on 2024-11-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="projects", to="tasks.team"
            ),
        ),
    ]
