# Generated by Django 4.1 on 2024-11-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_project_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="tasks.team"
            ),
        ),
    ]
