# Generated by Django 5.1.3 on 2024-11-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_deadline_alter_task_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("priority", "name")},
        ),
    ]
