# Generated by Django 5.1.3 on 2024-11-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Urgent"), (2, "High"), (3, "Medium"), (4, "Low")],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "In progress"), (3, "Completed")],
                default=1,
            ),
        ),
    ]
