# Generated by Django 5.1.3 on 2024-11-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": (
                    "name",
                    "priority",
                    "status",
                    "deadline",
                    "task_type",
                    "project",
                )
            },
        ),
    ]
